---
# tasks file for roles/netology_gitlab
- name: Check service facts
  ansible.builtin.service_facts:
- ansible.builtin.include_tasks: setup_gitlab_server.yml
  when: (role_gitlab == "server") and not ("gitlab-runsvdir.service" in ansible_facts.services)
- ansible.builtin.include_tasks: setup_gitlab_runner.yml
  when: (role_gitlab == "runner") and not ("gitlab-runner.service" in ansible_facts.services)
