---
- name: GitLab | Install Runner deb package
  become: true
  ansible.builtin.apt:
    update_cache: true
    deb: https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb
  environment: "{{ proxy_env }}"
- name: GitLab | Register Runner
  become: true
  ansible.builtin.shell: >
    gitlab-runner register
    --non-interactive
    --url "{{ gitlab_url }}"
    --registration-token "{{ gitlab_token }}"
    --description "{{ hostvars['gitlab-02']['ansible_hostname'] }}-{{ runner_executor }}-Runner"
    --executor "{{ runner_executor }}"
  changed_when: true
