---
- name: GitLab | Download Runner .deb package
  ansible.builtin.get_url:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb
    dest: /tmp/gitlab-runner_amd64.deb
    mode: 0644
  environment: "{{ proxy_env }}"
- name: GitLab | Install Runner .deb package
  become: true
  ansible.builtin.apt:
    update_cache: yes
    deb: /tmp/gitlab-runner_amd64.deb
  environment: "{{ proxy_env }}"
- name: GitLab | Register Runner
  become: true
  ansible.builtin.shell: >
    gitlab-runner register
    --non-interactive
    --url "{{ gitlab_url }}"
    --registration-token "{{ gitlab_token }}"
    --description "{{ hostvars['gitlab-02']['ansible_hostname'] }}-{{ runner_executor }}-Runner"
    --executor "{{ runner_executor }}"
