---
proxy_env:
  https_proxy: ""
  http_proxy: ""

## Cloud site: ######################
ansible_user: ubuntu
ansible_user_group: ubuntu

## Local site: ######################
#ansible_user: vagrant
#ansible_user_group: vagrant
#ansible_password: vagrant
