---
# handlers file for roles/netology_edge
- name: Edge | Restart NGINX
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
- name: Edge | Restart Tinyproxy
  become: true
  ansible.builtin.service:
    name: tinyproxy
    state: restarted
- name: Edge | Get SSL certificates
  become: true
  ansible.builtin.command: acme-nginx \
                          -d www.netology-stud.run.place \
                          -d gitlab.netology-stud.run.place \
                          -d grafana.netology-stud.run.place \
                          -d prometheus.netology-stud.run.place \
                          -d alertmanager.netology-stud.run.place
