---
- name: Configure Edge host
  hosts: edge
  roles:
    - netology_edge
- name: Get facts
  hosts: all
- name: Install MySQL
  hosts: mysql
  roles:
    - netology_mysql
- name: Install WordPress
  hosts: app
  roles:
    - netology_wordpress
- name: Install GitLab
  hosts: gitlab
  roles:
    - netology_gitlab
- name: Install Prometheos
  hosts: all
  roles:
    - netology_prom
