---
# vars file for roles/netology_wordpress
wordpress_packages:
  - nginx
  - php-fpm
  - php-mysql
  - php-curl
  - php-gd
  - php-intl
  - php-mbstring
  - php-soap
  - php-xml
  - php-xmlrpc
  - php-zip
