---
galaxy_info:
  author: netology-kononov
  description: Role for Prometheus stack installation in Netology graduate project
  company: netology-edu

  license: MIT

  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - "all"

  galaxy_tags: []

dependencies: []
